<?xml version="1.0" encoding="UTF-8"?>
<module external.linked.project.id=":Topics-Debugging_techniques-Debugging_an_Arithmetic_Exception_with_Logging:main" external.linked.project.path="$MODULE_DIR$/../../../../../Topics/Debugging techniques/Debugging an Arithmetic Exception with Logging" external.root.project.path="$MODULE_DIR$/../../../../.." external.system.id="GRADLE" external.system.module.group="Battleship with Java1_01" external.system.module.type="sourceSet" external.system.module.version="unspecified" type="JAVA_MODULE" version="4">
  <component name="NewModuleRootManager">
    <output url="file://$MODULE_DIR$/../../../../../Topics/Debugging techniques/Debugging an Arithmetic Exception with Logging/out/production/classes" />
    <exclude-output />
    <content url="file://$MODULE_DIR$/../../../../../Topics/Debugging techniques/Debugging an Arithmetic Exception with Logging/src">
      <sourceFolder url="file://$MODULE_DIR$/../../../../../Topics/Debugging techniques/Debugging an Arithmetic Exception with Logging/src" isTestSource="false" />
    </content>
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
  </component>
</module>